{
 "title": "Smart Home",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Room",
    "label": "Room",
    "query": "Living, Bedroom, Workroom, Dining"
   }
  ]
 },
 "panels": [
  {
   "title": "Living",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Living\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Temp\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: true)\n  |> yield(name: \"Current Temp\")"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Living\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Hum\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"Current Hum\")\n  \n\n"
    }
   ]
  },
  {
   "title": "Bedroom",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Bedroom\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Temp\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: true)\n  |> yield(name: \"Current Temp\")"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Bedroom\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Hum\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"Current Hum\")\n  \n\n"
    }
   ]
  },
  {
   "title": "Workroom",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Workroom\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Temp\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: true)\n  |> yield(name: \"Current Temp\")"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Workroom\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Hum\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"Current Hum\")\n  \n\n"
    }
   ]
  },
  {
   "title": "Dining",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Dining\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Temp\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: true)\n  |> yield(name: \"Current Temp\")"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Dining\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Hum\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"Current Hum\")\n  \n\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Living\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Temperature (Living)\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"Temperature (Living)\")"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Bedroom\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Temperature (Bedroom)\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"Temperature (Bedroom)\")"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Workroom\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Temperature (Workroom)\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"Temperature (Workroom)\")"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Dining\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Temperature (Dining)\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"Temperature (Dining)\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Living\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Humidity (Living)\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Humidity (Living)\")\n  \n\n"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Bedroom\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Humidity (Bedroom)\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Humidity (Bedroom)\")\n  \n\n"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Workroom\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Humidity (Workroom)\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Humidity (Workroom)\")\n  \n\n"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter Dining\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Humidity (Dining)\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Humidity (Dining)\")\n  \n\n"
    }
   ]
  },
  {
   "title": "Daily Uptime (Weekly Avg)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -56d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC Living\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"), createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> aggregateWindow(every: 1w, fn: mean, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Room: Living)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Room: Living)\"])\n  |> yield(name: \"Uptime (Room: Living)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -56d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC Bedroom\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"), createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> aggregateWindow(every: 1w, fn: mean, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Room: Bedroom)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Room: Bedroom)\"])\n  |> yield(name: \"Uptime (Room: Bedroom)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -56d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC Workroom\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"), createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> aggregateWindow(every: 1w, fn: mean, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Room: Workroom)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Room: Workroom)\"])\n  |> yield(name: \"Uptime (Room: Workroom)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -56d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC Dining\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"), createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> aggregateWindow(every: 1w, fn: mean, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Room: Dining)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Room: Dining)\"])\n  |> yield(name: \"Uptime (Room: Dining)\")"
    }
   ]
  },
  {
   "title": "Daily Uptime",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -14d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC Living\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Room: Living)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Room: Living)\"])\n  |> yield(name: \"Uptime (Room: Living)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -14d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC Bedroom\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Room: Bedroom)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Room: Bedroom)\"])\n  |> yield(name: \"Uptime (Room: Bedroom)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -14d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC Workroom\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Room: Workroom)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Room: Workroom)\"])\n  |> yield(name: \"Uptime (Room: Workroom)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -14d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC Dining\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Room: Dining)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Room: Dining)\"])\n  |> yield(name: \"Uptime (Room: Dining)\")"
    }
   ]
  },
  {
   "title": "Daily Uptime (Weekly Avg)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -56d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"ServiceName\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"ServiceName\", \"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active == 0)\n  |> map(fn: (r) => ({ _room: r.ServiceName, _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_room\", \"_time\", \"_value\"])\n  |> group(columns: [\"_room\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"), createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> aggregateWindow(every: 1w, fn: mean, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Mode: Dehumidification)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Mode: Dehumidification)\"])\n  |> yield(name: \"Uptime (Mode: Dehumidification)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -56d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or r[\"_field\"] == \"RotationSpeed\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"ServiceName\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"ServiceName\", \"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active > 0 and r.Fan_RotationSpeed < 10)\n  |> map(fn: (r) => ({ _room: r.ServiceName, _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_room\", \"_time\", \"_value\"])\n  |> group(columns: [\"_room\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"), createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> aggregateWindow(every: 1w, fn: mean, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Mode: Cooling/Silent)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Mode: Cooling/Silent)\"])\n  |> yield(name: \"Uptime (Mode: Cooling/Silent)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -56d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or r[\"_field\"] == \"RotationSpeed\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"ServiceName\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"ServiceName\", \"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active > 0 and r.Fan_RotationSpeed >= 10)\n  |> map(fn: (r) => ({ _room: r.ServiceName, _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_room\", \"_time\", \"_value\"])\n  |> group(columns: [\"_room\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"), createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> aggregateWindow(every: 1w, fn: mean, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: r._value}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Mode: Cooling/Auto)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Mode: Cooling/Auto)\"])\n  |> yield(name: \"Uptime (Mode: Cooling/Auto)\")"
    }
   ]
  },
  {
   "title": "Daily Uptime",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -14d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"ServiceName\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"ServiceName\", \"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active == 0)\n  |> map(fn: (r) => ({ _room: r.ServiceName, _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_room\", \"_time\", \"_value\"])\n  |> group(columns: [\"_room\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Mode: Dehumidification)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Mode: Dehumidification)\"])\n  |> yield(name: \"Uptime (Mode: Dehumidification)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -14d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or r[\"_field\"] == \"RotationSpeed\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"ServiceName\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"ServiceName\", \"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active > 0 and r.Fan_RotationSpeed < 10)\n  |> map(fn: (r) => ({ _room: r.ServiceName, _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_room\", \"_time\", \"_value\"])\n  |> group(columns: [\"_room\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Mode: Cooling/Silent)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Mode: Cooling/Silent)\"])\n  |> yield(name: \"Uptime (Mode: Cooling/Silent)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -14d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or r[\"_field\"] == \"RotationSpeed\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"ServiceName\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"ServiceName\", \"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active > 0 and r.Fan_RotationSpeed >= 10)\n  |> map(fn: (r) => ({ _room: r.ServiceName, _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_room\", \"_time\", \"_value\"])\n  |> group(columns: [\"_room\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (Mode: Cooling/Auto)\"})\n  |> keep(columns: [\"_time\", \"Uptime (Mode: Cooling/Auto)\"])\n  |> yield(name: \"Uptime (Mode: Cooling/Auto)\")"
    }
   ]
  },
  { "title": "${Room}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }, "repeat": "Room" },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Temp\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"Current Temp\")"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Hum\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Current Hum\")\n  \n\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 3, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Temp\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"Current Temp\")"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Temp (AC)\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"Current Temp (AC)\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CoolingThresholdTemperature\" or r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or r[\"_field\"] == \"RotationSpeed\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: r.Fan_RotationSpeed }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Rotation Speed (MODE: Cooling)\"})\n  |> keep(columns: [\"_time\", \"Rotation Speed (MODE: Cooling)\"])\n  |> yield(name: \"Rotation Speed (MODE: Cooling)\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CoolingThresholdTemperature\" or r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or r[\"_field\"] == \"RotationSpeed\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active == 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: r.Fan_RotationSpeed }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Rotation Speed (MODE: Dehumidification)\"})\n  |> keep(columns: [\"_time\", \"Rotation Speed (MODE: Dehumidification)\"])\n  |> yield(name: \"Rotation Speed (MODE: Dehumidification)\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 11, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Hum\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Current Hum\")\n  \n\n"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Hum (AC)\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Current Hum (AC)\")\n  "
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CoolingThresholdTemperature\" or r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or r[\"_field\"] == \"RotationSpeed\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: r.Fan_RotationSpeed }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Ratation Speed (MODE: Cooling)\"})\n  |> keep(columns: [\"_time\", \"Ratation Speed (MODE: Cooling)\"])\n  |> yield(name: \"Ratation Speed (MODE: Cooling)\")"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CoolingThresholdTemperature\" or r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or r[\"_field\"] == \"RotationSpeed\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active == 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: r.Fan_RotationSpeed }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Ratation Speed (MODE: Dehumidification)\"})\n  |> keep(columns: [\"_time\", \"Ratation Speed (MODE: Dehumidification)\"])\n  |> yield(name: \"Ratation Speed (MODE: Dehumidification)\")"
    }
   ]
  },
  {
   "title": "Temperature-Humidity Chart",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\" or r[\"_measurement\"] == \"HumiditySensor\" or r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\" or r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or (r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\" and r[\"_field\"] == \"CurrentTemperature\") or (r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\" and r[\"_field\"] == \"CurrentRelativeHumidity\"))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, _ac_mode: r.Fan_On + r.HeaterCooler_Active, _temperature: r.TemperatureSensor_CurrentTemperature, _humidity: r.HumiditySensor_CurrentRelativeHumidity }))\n  |> filter(fn: (r) => r._ac_mode == 0)"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\" or r[\"_measurement\"] == \"HumiditySensor\" or r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\" or r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or (r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\" and r[\"_field\"] == \"CurrentTemperature\") or (r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\" and r[\"_field\"] == \"CurrentRelativeHumidity\"))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, _ac_mode: r.Fan_On + r.HeaterCooler_Active, _temperature: r.TemperatureSensor_CurrentTemperature, _humidity: r.HumiditySensor_CurrentRelativeHumidity }))\n  |> filter(fn: (r) => r._ac_mode == 1)"
    },
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\" or r[\"_measurement\"] == \"HumiditySensor\" or r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\" or r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\" or (r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\" and r[\"_field\"] == \"CurrentTemperature\") or (r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\" and r[\"_field\"] == \"CurrentRelativeHumidity\"))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, _ac_mode: r.Fan_On + r.HeaterCooler_Active, _temperature: r.TemperatureSensor_CurrentTemperature, _humidity: r.HumiditySensor_CurrentRelativeHumidity }))\n  |> filter(fn: (r) => r._ac_mode == 2)"
    }
   ]
  },
  {
   "title": "Daily Uptime",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -14d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active == 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: true)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (MODE: Dehumidification)\"})\n  |> keep(columns: [\"_time\", \"Uptime (MODE: Dehumidification)\"])\n  |> yield(name: \"Uptime (MODE: Dehumidification)\")"
    },
    {
     "query": "import \"math\"\nimport \"timezone\"\n\nfrom(bucket: \"homebridge\")\n  |> range(start: -14d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeaterCooler\" or r[\"_measurement\"] == \"Fan\")\n  |> filter(fn: (r) => r[\"ServiceName\"] == \"Daikin AC ${Room}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Active\" or r[\"_field\"] == \"On\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => r.Fan_On > 0 and r.HeaterCooler_Active > 0)\n  |> map(fn: (r) => ({ _time: r._time, _value: 1 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: 5m, fn: max, createEmpty: true)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value * 5}))\n  |> aggregateWindow(every: 1d, fn: sum, location: timezone.location(name: \"Asia/Singapore\"))\n  |> map(fn: (r) => ({_time: r._time, _value: float(v: r._value) / 60.0}))\n  |> timeShift(duration: 8h)\n  |> timeShift(duration: -1ms)\n  |> truncateTimeColumn(unit: 1d)\n  |> timeShift(duration: 16h)\n  |> rename(columns: {\"_time\": \"_time\", \"_value\": \"Uptime (MODE: Cooling)\"})\n  |> keep(columns: [\"_time\", \"Uptime (MODE: Cooling)\"])\n  |> yield(name: \"Uptime (MODE: Cooling)\")"
    }
   ]
  },
  {
   "title": "Temperature Histogram",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TemperatureSensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Temp\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"Current Temp\")"
    }
   ]
  },
  {
   "title": "Humidity Histogram",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"homebridge\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HumiditySensor\")\n  |> filter(fn: (r) => r[\"ServiceName\"]  == \"SwitchBot Meter ${Room}\")\n  |> map(fn: (r) => ({ _time: r._time, _measurement: \"Current Hum\", _value: r._value }))\n  |> keep(columns: [\"_time\", \"_measurement\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Current Hum\")\n  \n\n"
    }
   ]
  }
 ]
}